### ISSUE TITLE
Mistake in the SDNet architecture

### ISSUE THREAD

**Issue by mdessl** [spthermo/SDNet#1]
Hi there, 
in line 238 of SDNet/sdnet.py the modality encoder takes the anatomy encoding and x as an input. Instead of the initial input x i think this needs to be the reconstructed image (ie. _, mu_out_tilde, _ = self.m_encoder(a_out, reco)). Please feel free to correct me! Thanks :)

**Comment by spthermo** [comment]
Hi, if you see the variant A model (figure in the readme) there is a dot-line indicating the propagation of the anatomy factors to the input of the modality VAE. We concatenate the anatomy factors with input x as we found that this "guides" the appearance disentanglement. You can check the relevant section 3.1.2 of the original paper (https://arxiv.org/pdf/1903.09467v3.pdf).

Cheers,
