### ISSUE TITLE
modality factor reconstruction

### ISSUE THREAD

**Issue by mdessl** [spthermo/SDNet#2]
Thanks for your reply. It makes sense to me that the initial forward pass in the modality encoder receives the anatomy encoding and the input image. However, I am referring to the modality factor reconstruction  (section 3.3.1) to mitigate posterior collapse. There the vae encodes the reconstructed image. The resulting encoding is then compared to the modality encoding of the initial input image. This is not done in the code as far I see it. The regression loss instead takes the mu and z of the same inputs. Cheers, Markus

**Comment by spthermo** [comment]
You are absolutely right! This was a result of a bad c/p of the code. The correct forward pass should be:
`a_out_tilde = self.a_encoder(reco)`

`_, mu_tilde, _ =  self.m_encoder(a_out_tilde, reco,)`

I will update the code accordingly. Thanks for the feedback.
